### 查询服务实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/nacos-client/service-instance
Accept: application/json


### 查看 Sleuth 跟踪信息
GET http://127.0.0.1:9001/edkso/ecommerce-nacos-client/sleuth/trace-info
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImxpbmNoZW5nXCJ9IiwianRpIjoiNzg0M2NlZTctM2E0NC00NzFkLTk0NWItYjE4YWQ4ZDU5MTkwIiwiZXhwIjoxNjgyMTc5MjAwfQ.NGtNcVhXh03YRwm7UEjl5pDWBmLoJBcDdb_4nHVa1thYVOHha9mq4bm6DlM7ag3k64jp6lI8masXn_s4bNVPtmJTpI9CM68pZUj7OqVPgXWbrjYI8v9TzA8-wy9Jd7E6ycoRvTVgXhMX9cX-_CaVvQovC1EIJV80SLV6w9FHUHNFHByowTaVSE3utlSCJLw--Uspsf6u7ovK5ttQfi7w-_GvJr3rhQSU3LRGhPWlLNsLZVUCj0UyK9r78lWdcav-0TBCb2y43gtlHmzyiVvd3yDQ2EwnRY_a9E-DGJtrpHLT9NP-PX4ReFP2Rzb2YA6Z2tvlI-VxuZgNyigrWtVJJw
token: edkso
