### 查询服务
GET http://127.0.0.1:9001/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjE0LFwidXNlcm5hbWVcIjpcInpoYW5nemhpZmVuZ1wifSIsImp0aSI6IjMzNjlhMDI3LTc5MWYtNDMwYy1iNjNiLWM5YWU3MDU3MjA2ZiIsImV4cCI6MTY4MTgzMzYwMH0.fpnux3kaZquHE55ZHoedXFo9qxnAqLEDzLWaBxxNP0xMaIU6TPv55OxwZBe7i3KUCGv4VYJd5fW8qC5m1fZBhLjk2wFLeCYZIiSnV7onhMVAm2TVspMWdaWhaZ222eJeq5NOc0hBAywTqXGPO5HIT0zl0csn0kkwEAutFRNlHw09ntgMq5FNvq4IkazBqw3Cu7gvmmtDr84IEzjXbMoqKa6bin0qJRSUIxv8ytU08KZVSlST5E9cD-kC-154KManRumLNi-nZRYdvmGWb2ofNqA2POrh5Jr_pHlKYJoIoBl-NtN-2Oq5-M3Rt92cbWcuKxlO1dwiOrSwwvfrBKvDqA
token: edkso
